### ISSUE TITLE
Latest patch and TTT updates seem to cause problems with loading games with this mod

### ISSUE THREAD

**Issue by SimpleFish5655** [Envibel/ComeAndGetMe#2]
The latest patch 2.02c and Vek's updates to TTT seem to cause slow load times with this mod enabled (for both fresh characters and existing savegames).

I get a bunch of repeating errors from the GameLog.
[Error.txt](https://github.com/Envibel/ComeAndGetMe/files/9838590/Error.txt)

Disabling this mod resolves the slow loading times

**Comment by Envibel** [comment]
Thanks for reporting this, I'll take a look!

**Comment by Envibel** [comment]
This is resolved with the latest release. Thanks again for reporting!
